server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 120S

      routes:
        # RUTAS AL MONOLITO
        - id: ms-monolito
          uri: https://inmobiliariaivan.onrender.com
          predicates:
            - Path=/api/auth/**, /api/public/**, /api/distritos/**, /api/usuarios/**, /api/separaciones/**, /api/clientes/**, /api/contratos/**, /api/vendedores/**, /api/lotes/**, /api/programas/**,/api/parceleros/**, /api/letras/**, /api/dashboard/**, /api/gateway/inscripciones/**, /api/gateway/recibos/**, /chat/**, /api/archivos/**, /ws/**, /api/mensajes/**,/api/pagos/**
          filters:
            # ✅ NUEVO: Inyecta el secreto en TODAS las rutas hacia el monolito
            - AddRequestHeader=X-Gateway-Secret, ${GATEWAY_SECRET}
            - name: Retry
              args:
                retries: 3
                series: SERVER_ERROR
                exceptions: java.io.IOException, reactor.netty.http.client.PrematureCloseException
                methods: GET, POST
                backoff:
                  firstBackoff: 2s
                  maxBackoff: 6s
                  factor: 2

        # RUTAS AL MICROSERVICIO
        - id: ms-servicios-basicos
          uri: https://serviciobasico.onrender.com
          predicates:
            - Path=/api/recibos/**, /api/configuraciones/**, /api/pagos-sb/**, /api/inscripciones/**
          filters:
            # ✅ NUEVO: Inyecta el secreto en TODAS las rutas hacia el microservicio
            - AddRequestHeader=X-Gateway-Secret, ${GATEWAY_SECRET}
            - name: Retry
              args:
                retries: 3
                series: SERVER_ERROR
                methods: GET, POST

jwt:
  secret-key: ${JWT_SECRET}

gateway:
  secret-key: ${GATEWAY_SECRET}