server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 2
            statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR
            methods: GET
            backoff:
              firstBackoff: 200ms
              maxBackoff: 1000ms
              factor: 2
              basedOnPreviousValue: false

      httpclient:
        connect-timeout: 10000
        response-timeout: 160s
        pool:
          type: fixed
          max-idle-time: 45s
          max-life-time: 180s

      routes:
        # RUTAS AL MONOLITOs
        - id: ms-monolito
          uri: https://inmobiliariaivan.onrender.com
          predicates:
            - Path=/api/auth/**, /api/public/**, /api/distritos/**, /api/usuarios/**, /api/separaciones/**, /api/clientes/**, /api/contratos/**, /api/vendedores/**, /api/lotes/**, /api/programas/**, /api/parceleros/**, /api/letras/**, /api/dashboard/**, /api/gateway/inscripciones/**, /api/gateway/recibos/**, /chat/**, /api/archivos/**, /ws/**, /api/mensajes/**, /api/pagos/**, /api/tipo-cambio/**, /api/moras/**, /api/comprobantes/**
          filters:
            - AddRequestHeader=X-Gateway-Secret, ${GATEWAY_SECRET}
            - name: Retry
              args:
                retries: 2
                exceptions: java.io.IOException, reactor.netty.http.client.PrematureCloseException
                methods: GET
                backoff:
                  firstBackoff: 300ms
                  maxBackoff: 2s
                  factor: 2
                  basedOnPreviousValue: false

        # RUTAS AL MICROSERVICIO
        - id: ms-servicios-basicos
          uri: https://serviciobasico.onrender.com
          predicates:
            - Path=/api/recibos/**, /api/configuraciones/**, /api/pagos-sb/**, /api/inscripciones/**
          filters:
            - AddRequestHeader=X-Gateway-Secret, ${GATEWAY_SECRET}
            - name: Retry
              args:
                retries: 2
                exceptions: java.io.IOException, reactor.netty.http.client.PrematureCloseException
                methods: GET
                backoff:
                  firstBackoff: 300ms
                  maxBackoff: 2s
                  factor: 2
                  basedOnPreviousValue: false

jwt:
  secret-key: ${JWT_SECRET}

gateway:
  secret-key: ${GATEWAY_SECRET}